// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	domain "clean_task_manager_api_tested/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TaskRepositoryInteface is an autogenerated mock type for the TaskRepositoryInteface type
type TaskRepositoryInteface struct {
	mock.Mock
}

// Create provides a mock function with given fields: c, task
func (_m *TaskRepositoryInteface) Create(c context.Context, task *domain.Task) (*domain.Task, error) {
	ret := _m.Called(c, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Task) (*domain.Task, error)); ok {
		return rf(c, task)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Task) *domain.Task); ok {
		r0 = rf(c, task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Task) error); ok {
		r1 = rf(c, task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: c, taskID
func (_m *TaskRepositoryInteface) DeleteTask(c context.Context, taskID string) error {
	ret := _m.Called(c, taskID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(c, taskID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllTasks provides a mock function with given fields: c
func (_m *TaskRepositoryInteface) GetAllTasks(c context.Context) ([]domain.Task, error) {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 []domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Task, error)); ok {
		return rf(c)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Task); ok {
		r0 = rf(c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(c)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskByID provides a mock function with given fields: c, taskID
func (_m *TaskRepositoryInteface) GetTaskByID(c context.Context, taskID string) (*domain.Task, error) {
	ret := _m.Called(c, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Task, error)); ok {
		return rf(c, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Task); ok {
		r0 = rf(c, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(c, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: c, taskID, task
func (_m *TaskRepositoryInteface) UpdateTask(c context.Context, taskID string, task *domain.Task) error {
	ret := _m.Called(c, taskID, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Task) error); ok {
		r0 = rf(c, taskID, task)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskRepositoryInteface creates a new instance of TaskRepositoryInteface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepositoryInteface(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepositoryInteface {
	mock := &TaskRepositoryInteface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
